# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/segfault/Projects/IoFarmer-OpenGL

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/segfault/Projects/IoFarmer-OpenGL

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles /home/segfault/Projects/IoFarmer-OpenGL//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named files

# Build rule for target.
files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 files
.PHONY : files

# fast build rule for target.
files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/build
.PHONY : files/fast

#=============================================================================
# Target rules for targets named polygon

# Build rule for target.
polygon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 polygon
.PHONY : polygon

# fast build rule for target.
polygon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon.dir/build.make CMakeFiles/polygon.dir/build
.PHONY : polygon/fast

#=============================================================================
# Target rules for targets named Graphics

# Build rule for target.
Graphics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Graphics
.PHONY : Graphics

# fast build rule for target.
Graphics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphics.dir/build.make CMakeFiles/Graphics.dir/build
.PHONY : Graphics/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named IoFarmer.out

# Build rule for target.
IoFarmer.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IoFarmer.out
.PHONY : IoFarmer.out

# fast build rule for target.
IoFarmer.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IoFarmer.out.dir/build.make CMakeFiles/IoFarmer.out.dir/build
.PHONY : IoFarmer.out/fast

Graphics.o: Graphics.c.o
.PHONY : Graphics.o

# target to build an object file
Graphics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphics.dir/build.make CMakeFiles/Graphics.dir/Graphics.c.o
.PHONY : Graphics.c.o

Graphics.i: Graphics.c.i
.PHONY : Graphics.i

# target to preprocess a source file
Graphics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphics.dir/build.make CMakeFiles/Graphics.dir/Graphics.c.i
.PHONY : Graphics.c.i

Graphics.s: Graphics.c.s
.PHONY : Graphics.s

# target to generate assembly for a file
Graphics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Graphics.dir/build.make CMakeFiles/Graphics.dir/Graphics.c.s
.PHONY : Graphics.c.s

files.o: files.c.o
.PHONY : files.o

# target to build an object file
files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/files.c.o
.PHONY : files.c.o

files.i: files.c.i
.PHONY : files.i

# target to preprocess a source file
files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/files.c.i
.PHONY : files.c.i

files.s: files.c.s
.PHONY : files.s

# target to generate assembly for a file
files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/files.c.s
.PHONY : files.c.s

glad/src/glad.o: glad/src/glad.c.o
.PHONY : glad/src/glad.o

# target to build an object file
glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.o
.PHONY : glad/src/glad.c.o

glad/src/glad.i: glad/src/glad.c.i
.PHONY : glad/src/glad.i

# target to preprocess a source file
glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.i
.PHONY : glad/src/glad.c.i

glad/src/glad.s: glad/src/glad.c.s
.PHONY : glad/src/glad.s

# target to generate assembly for a file
glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/glad.dir/build.make CMakeFiles/glad.dir/glad/src/glad.c.s
.PHONY : glad/src/glad.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IoFarmer.out.dir/build.make CMakeFiles/IoFarmer.out.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IoFarmer.out.dir/build.make CMakeFiles/IoFarmer.out.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IoFarmer.out.dir/build.make CMakeFiles/IoFarmer.out.dir/main.c.s
.PHONY : main.c.s

polygon.o: polygon.c.o
.PHONY : polygon.o

# target to build an object file
polygon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon.dir/build.make CMakeFiles/polygon.dir/polygon.c.o
.PHONY : polygon.c.o

polygon.i: polygon.c.i
.PHONY : polygon.i

# target to preprocess a source file
polygon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon.dir/build.make CMakeFiles/polygon.dir/polygon.c.i
.PHONY : polygon.c.i

polygon.s: polygon.c.s
.PHONY : polygon.s

# target to generate assembly for a file
polygon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/polygon.dir/build.make CMakeFiles/polygon.dir/polygon.c.s
.PHONY : polygon.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Graphics"
	@echo "... IoFarmer.out"
	@echo "... files"
	@echo "... glad"
	@echo "... polygon"
	@echo "... Graphics.o"
	@echo "... Graphics.i"
	@echo "... Graphics.s"
	@echo "... files.o"
	@echo "... files.i"
	@echo "... files.s"
	@echo "... glad/src/glad.o"
	@echo "... glad/src/glad.i"
	@echo "... glad/src/glad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... polygon.o"
	@echo "... polygon.i"
	@echo "... polygon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

