
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (Project)"
    message: |
      The system is: Linux - 6.1.14-200.fc37.x86_64 - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (Project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/cc 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is Clang, found in:
        /home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/3.26.0-rc4/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (Project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB"
      binary: "/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB
        
        Run Build Command(s):/usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_7fb89/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_7fb89.dir/build.make CMakeFiles/cmTC_7fb89.dir/build
        gmake[1]: Entering directory '/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB'
        Building C object CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o
        /usr/bin/cc   -v -MD -MT CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake/Modules/CMakeCCompilerABI.c
        clang version 15.0.7 (Fedora 15.0.7-1.fc37)
        Target: x86_64-redhat-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Selected multilib: .;@m64
         (in-process)
         "/usr/bin/clang-15" -cc1 -triple x86_64-redhat-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB -resource-dir /usr/lib64/clang/15.0.7 -dependency-file CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /usr/lib64/clang/15.0.7/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -x c /usr/share/cmake/Modules/CMakeCCompilerABI.c
        clang -cc1 version 15.0.7 based upon LLVM 15.0.7 default target x86_64-redhat-linux-gnu
        ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include"
        ignoring nonexistent directory "/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib64/clang/15.0.7/include
         /usr/local/include
         /usr/include
        End of search list.
        Linking C executable cmTC_7fb89
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7fb89.dir/link.txt --verbose=1
        /usr/bin/cc  -v CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -o cmTC_7fb89 
        clang version 15.0.7 (Fedora 15.0.7-1.fc37)
        Target: x86_64-redhat-linux-gnu
        Thread model: posix
        InstalledDir: /usr/bin
        Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12
        Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12
        Candidate multilib: .;@m64
        Candidate multilib: 32;@m32
        Selected multilib: .;@m64
         "/usr/bin/ld" --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_7fb89 /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/12 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o
        gmake[1]: Leaving directory '/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB'
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (Project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/lib64/clang/15.0.7/include]
          add: [/usr/local/include]
          add: [/usr/include]
        end of search list found
        collapse include dir [/usr/lib64/clang/15.0.7/include] ==> [/usr/lib64/clang/15.0.7/include]
        collapse include dir [/usr/local/include] ==> [/usr/local/include]
        collapse include dir [/usr/include] ==> [/usr/include]
        implicit include dirs: [/usr/lib64/clang/15.0.7/include;/usr/local/include;/usr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:152 (message)"
      - "/usr/share/cmake/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (Project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: /home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB]
        ignore line: []
        ignore line: [Run Build Command(s):/usr/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_7fb89/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_7fb89.dir/build.make CMakeFiles/cmTC_7fb89.dir/build]
        ignore line: [gmake[1]: Entering directory '/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB']
        ignore line: [Building C object CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o]
        ignore line: [/usr/bin/cc   -v -MD -MT CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake/Modules/CMakeCCompilerABI.c]
        ignore line: [clang version 15.0.7 (Fedora 15.0.7-1.fc37)]
        ignore line: [Target: x86_64-redhat-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/bin]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12]
        ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        ignore line: [ (in-process)]
        ignore line: [ "/usr/bin/clang-15" -cc1 -triple x86_64-redhat-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB -resource-dir /usr/lib64/clang/15.0.7 -dependency-file CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -sys-header-deps -internal-isystem /usr/lib64/clang/15.0.7/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -fdebug-compilation-dir=/home/segfault/Projects/IoFarmer-OpenGL/CMakeFiles/CMakeScratch/TryCompile-J32PsB -ferror-limit 19 -fgnuc-version=4.2.1 -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -x c /usr/share/cmake/Modules/CMakeCCompilerABI.c]
        ignore line: [clang -cc1 version 15.0.7 based upon LLVM 15.0.7 default target x86_64-redhat-linux-gnu]
        ignore line: [ignoring nonexistent directory "/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../x86_64-redhat-linux/include"]
        ignore line: [ignoring nonexistent directory "/include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/lib64/clang/15.0.7/include]
        ignore line: [ /usr/local/include]
        ignore line: [ /usr/include]
        ignore line: [End of search list.]
        ignore line: [Linking C executable cmTC_7fb89]
        ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7fb89.dir/link.txt --verbose=1]
        ignore line: [/usr/bin/cc  -v CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -o cmTC_7fb89 ]
        ignore line: [clang version 15.0.7 (Fedora 15.0.7-1.fc37)]
        ignore line: [Target: x86_64-redhat-linux-gnu]
        ignore line: [Thread model: posix]
        ignore line: [InstalledDir: /usr/bin]
        ignore line: [Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12]
        ignore line: [Selected GCC installation: /usr/bin/../lib/gcc/x86_64-redhat-linux/12]
        ignore line: [Candidate multilib: .]
        ignore line: [@m64]
        ignore line: [Candidate multilib: 32]
        ignore line: [@m32]
        ignore line: [Selected multilib: .]
        ignore line: [@m64]
        link line: [ "/usr/bin/ld" --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o cmTC_7fb89 /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtbegin.o -L/usr/bin/../lib/gcc/x86_64-redhat-linux/12 -L/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/lib -L/usr/lib CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtend.o /usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o]
          arg [/usr/bin/ld] ==> ignore
          arg [--hash-style=gnu] ==> ignore
          arg [--build-id] ==> ignore
          arg [--eh-frame-hdr] ==> ignore
          arg [-m] ==> ignore
          arg [elf_x86_64] ==> ignore
          arg [-dynamic-linker] ==> ignore
          arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
          arg [-o] ==> ignore
          arg [cmTC_7fb89] ==> ignore
          arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o] ==> obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o]
          arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o] ==> obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o]
          arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtbegin.o] ==> obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtbegin.o]
          arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/12] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/12]
          arg [-L/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64] ==> dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64]
          arg [-L/lib/../lib64] ==> dir [/lib/../lib64]
          arg [-L/usr/lib/../lib64] ==> dir [/usr/lib/../lib64]
          arg [-L/lib] ==> dir [/lib]
          arg [-L/usr/lib] ==> dir [/usr/lib]
          arg [CMakeFiles/cmTC_7fb89.dir/CMakeCCompilerABI.c.o] ==> ignore
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [-lc] ==> lib [c]
          arg [-lgcc] ==> lib [gcc]
          arg [--as-needed] ==> ignore
          arg [-lgcc_s] ==> lib [gcc_s]
          arg [--no-as-needed] ==> ignore
          arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtend.o] ==> obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtend.o]
          arg [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o] ==> obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crt1.o] ==> [/usr/lib64/crt1.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crti.o] ==> [/usr/lib64/crti.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtbegin.o] ==> [/usr/lib/gcc/x86_64-redhat-linux/12/crtbegin.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/crtend.o] ==> [/usr/lib/gcc/x86_64-redhat-linux/12/crtend.o]
        collapse obj [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64/crtn.o] ==> [/usr/lib64/crtn.o]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/12] ==> [/usr/lib/gcc/x86_64-redhat-linux/12]
        collapse library dir [/usr/bin/../lib/gcc/x86_64-redhat-linux/12/../../../../lib64] ==> [/usr/lib64]
        collapse library dir [/lib/../lib64] ==> [/lib64]
        collapse library dir [/usr/lib/../lib64] ==> [/usr/lib64]
        collapse library dir [/lib] ==> [/lib]
        collapse library dir [/usr/lib] ==> [/usr/lib]
        implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
        implicit objs: [/usr/lib64/crt1.o;/usr/lib64/crti.o;/usr/lib/gcc/x86_64-redhat-linux/12/crtbegin.o;/usr/lib/gcc/x86_64-redhat-linux/12/crtend.o;/usr/lib64/crtn.o]
        implicit dirs: [/usr/lib/gcc/x86_64-redhat-linux/12;/usr/lib64;/lib64;/lib;/usr/lib]
        implicit fwks: []
      
      
...
